export const users = [
  {
    id: "t9KND5pY8UUi0zX_qp7AL",
    name: "Mykola",
    login: "MK",
    password: "123",
    status: "active",
  },
  {
    id: "уNvoW9QKeOp2P7lEhdfT",
    name: "Irina",
    login: "Ira",
    password: "456",
    status: "active",
  },
  {
    id: "CmQ2o1fzR7SxLvPZDABY",
    name: "Petro",
    login: "Petro",
    password: "789",
    status: "active",
  },
  {
    id: "DqPlzOY9R7JmUv2ScwXf",
    name: "Oksana",
    login: "Oksana",
    password: "abc",
    status: "active",
  },
  {
    id: "5iU9z8Q1jP7b0Nv2LtWa",
    name: "Andriy",
    login: "Andriy",
    password: "def",
    status: "active",
  },
  {
    id: "K0jS7N8Yv2QdLp7RwIAC",
    name: "Maria",
    login: "Maria",
    password: "ghi",
    status: "active",
  },
  {
    id: "L0zO7Tj9R2SmUvDcXwPf",
    name: "Oleg",
    login: "Oleg",
    password: "jkl",
    status: "active",
  },
  {
    id: "W9Yv2Qc0Pj7Lp7RzIuAS",
    name: "Natalia",
    login: "Natalia",
    password: "mno",
    status: "active",
  },
  {
    id: "X1p7Rj9OzDc7Sv2MfUwL",
    name: "Serhiy",
    login: "Serhiy",
    password: "pqr",
    status: "active",
  },
  {
    id: "Y8v2j7R0Lp7uAdPc9bKi",
    name: "Yulia",
    login: "Yulia",
    password: "stu",
    status: "active",
  },
];
